name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  generate-projects:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Batch
          - pattern: "Batch ETL"
            stack: "DuckDB Local"

          - pattern: "Batch ETL"
            stack: "dbt + DuckDB"

          # Analytics
          - pattern: "Analytics"
            stack: "dbt + DuckDB"

          # Medallion
          - pattern: "Medallion"
            stack: "Spark + MinIO"

          # ELT
          - pattern: "ELT"
            stack: "Airflow + Postgres"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install degen
        run: pip install .

      - name: Cleanup old project
        run: rm -rf test_project

      - name: Generate project
        run: |
          degen init \
            --name test_project \
            --pattern "${{ matrix.pattern }}" \
            --stack "${{ matrix.stack }}"

      - name: Install project dependencies
        run: |
          cd test_project
          make install

      - name: Run project
        run: |
          cd test_project
          make run || true

      - name: Validate Docker Compose
        run: |
          cd test_project
          make docker-validate